### ISSUE TITLE
https://www.facebook.com/nilufa.yasmin.31508

### ISSUE THREAD

**Issue by BAPPIROY123** [fikrado/fikrado.py#25]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lucifar121** [comment]
Hi i am lucifar121

**Comment by Lucifar121** [comment]
https://www.facebook.com/profile.php?id=100093658220333&mibextid=ZbWKwL

**Comment by fikrado** [comment]
bots

**Comment by 0160688** [comment]
https://www.facebook.com/profile.php?id=100093658220333&mibextid=ZbWKwL

**Comment by 0160688** [comment]
https://www.facebook.com/profile.php?id=100093658220333&mibextid=ZbWKwL
