### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by Anonim1w** [fikrado/fikrado.py#3]
~/fikrado.py $ python2 fikrado.py
Traceback (most recent call last):
  File "fikrado.py", line 5, in <module>
    import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
ImportError: No module named requests

What is this ? This dont work

**Comment by sioud-web** [comment]
Just try to -m pip install requests
Before that try to pip Uninstall it

**Comment by fikrado** [comment]
Fixed

**Comment by fikrado** [comment]
Fixed it all ready

**Comment by MRJ-Badshah** [comment]
@fikrado how to fix this

**Comment by MRJ-Badshah** [comment]
I can't understand
